<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Add Customer Test"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="0.000">
  <properties />
            <testcase name="addCustomer" time="0.000" classname="testcases.AddCustomerTest">
                <failure type="org.testng.TestNGException"
                  message="
Method public void testcases.AddCustomerTest.addCustomer(java.lang.String,java.lang.String) throws java.lang.InterruptedException requires a @DataProvider named : getData"
              >
<![CDATA[org.testng.TestNGException: 
Method public void testcases.AddCustomerTest.addCustomer(java.lang.String,java.lang.String) throws java.lang.InterruptedException requires a @DataProvider named : getData
  org.testng.internal.Parameters.findDataProvider(Parameters.java:526)
  org.testng.internal.Parameters.handleParameters(Parameters.java:763)
  org.testng.internal.Parameters.handleParameters(Parameters.java:728)
  org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)
  org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)
  org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:917)
  org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
  org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
  org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
  java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
  org.testng.TestRunner.privateRun(TestRunner.java:806)
  org.testng.TestRunner.run(TestRunner.java:601)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
  org.testng.SuiteRunner.run(SuiteRunner.java:330)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
  org.testng.TestNG.runSuites(TestNG.java:1099)
  org.testng.TestNG.run(TestNG.java:1067)
  com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
  com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
